
##### Absolute path where PyPSA-X is cloned
rootpath: 



##### plot network
bus_sizes: 0.0008
bus_colors: black
boundaries_onshore: [-9.93, 4.11, 35.61, 44.18]
boundaries_offshore: [-14, 6.35, 35, 47]



##### functions: map_add_...
map_add_features:
  color_BORDERS: black
  color_COASTLINE: black
  color_LAND: beige
  color_OCEAN: none
  linewidth: 1

map_add_features_line:
  color_BORDERS: black
  color_COASTLINE: black
  color_LAND: none
  color_OCEAN: none
  linewidth: 1

map_add_region:
  color_onshore: wheat
  color_offshore: aliceblue
  edgecolor: black
  lw: 0.2



##### functions: map_network_...
map_network_generators:
  cmap: viridis
  edgecolor: black
  lw: 0.2

map_network_generatorst_pmaxpu:
  cmap: viridis
  edgecolor: black
  lw: 0.2

map_network_links:
  cmap: Reds
  edgecolor: black
  lw: 0.2

map_network_loadst_pset:
  cmap: cividis
  edgecolor: black
  lw: 0.2

map_network_storage_units:
  cmap: viridis
  edgecolor: black
  lw: 0.2

map_network_stores:
  cmap: Blues
  edgecolor: black
  lw: 0.2



##### functions: map_NUTS_...
map_NUTS_generators:
  cmap: viridis
  edgecolor: black
  lw: 0.2

map_NUTS_links:
  cmap: Reds
  edgecolor: black
  lw: 0.2

map_NUTS_loadst_pset:
  cmap: cividis
  edgecolor: black
  lw: 0.2

map_NUTS_storage_units:
  cmap: viridis
  edgecolor: black
  lw: 0.2

map_NUTS_stores:
  cmap: Blues
  edgecolor: black
  lw: 0.2


